name: flutter_fast_cli
description: Build Flutter Apps Faster. Generate boilerplate code for apps that require authentication, subscriptions, and more
version: 1.1.2
homepage: https://codeotr.github.io/flutter-fast-guide/
repository: https://github.com/CodeOTR/flutter_fast_cli
# flutter pub publish --dry-run

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  cli_util: ^0.4.0
  io: ^1.0.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0

# https://dart.dev/tools/pub/cmd/pub-global#configuring-package-executables
executables:
  fast:

# https://dart.dev/tools/pub/pubspec#screenshots
screenshots:
  - description: "Flutter Fast"
    path: assets/flutter-fast.png

false_secrets:
  - /flutterfast/android/app/google-services.json
  - /flutterfast/ios/Runner/GoogleService-Info.plist
  - /flutterfast/macos/Runner/GoogleService-Info.plist

topics:
  - boilerplate
  - cli
  - flutter
  - template