name: flutter_fast_cli
description: Build Flutter Apps Faster. Generate boilerplate code for apps that require authentication, subscriptions, and more
version: 2.0.0
homepage: https://github.com/CodeOTR/flutter_fast_cli
repository: https://github.com/CodeOTR/flutter_fast_cli
documentation: https://pub.dev/documentation/flutter_fast_cli/latest/
# flutter pub publish --dry-run

environment:
  sdk: ^3.1.0

# Add regular dependencies here.
dependencies:
  auto_route: ^8.1.3
  collection: ^1.18.0
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  in_app_review: ^2.0.9
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  shared_preferences: ^2.2.3
  universal_io: ^2.2.2
  universal_html: ^2.2.4
  url_launcher: ^6.2.6
  purchases_flutter: ^6.29.0
  google_sign_in: ^6.2.1
  mask_text_input_formatter: ^2.9.0
  sign_in_with_apple: ^6.1.0
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4
  firebase_core: ^2.31.1
  amplitude_flutter: ^3.16.2
  sentry_flutter: ^8.2.0
  args: ^2.4.2
  cli_util: ^0.4.0
  http: ^1.0.0
  io: ^1.0.4
  mason: ^0.1.0-dev.56
  recase: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  auto_route_generator: ^8.0.0
  firebase_remote_config: ^4.4.7
  lints: ^2.0.0
  test: ^1.21.0

assets:
   - assets/bundles

# https://dart.dev/tools/pub/cmd/pub-global#configuring-package-executables
executables:
  fast:

# https://dart.dev/tools/pub/pubspec#screenshots
screenshots:
  - description: "Flutter Fast"
    path: assets/flutter-fast.png

false_secrets:
  - /flutterfast/android/app/google-services.json
  - /flutterfast/ios/Runner/GoogleService-Info.plist
  - /flutterfast/macos/Runner/GoogleService-Info.plist
  - /flutterfast_offline/android/app/google-services.json
  - /flutterfast_offline/ios/Runner/GoogleService-Info.plist
  - /flutterfast_offline/macos/Runner/GoogleService-Info.plist
  - /flutterfast/web/index.html

topics:
  - boilerplate
  - cli
  - flutter
  - template