name: flutterfast_online_auth
description: Build Flutter apps fast.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplitude_flutter: ^3.16.2
  appwrite: ^12.0.3
  auto_route: ^8.1.3
  cloud_firestore: ^4.17.2
  collection: ^1.18.0
  crypto: ^3.0.3
  firebase_analytics: ^10.10.4
  firebase_auth: ^4.19.4
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.4
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0  
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_mobile_ads: ^5.1.0
  google_sign_in: ^6.2.1
  http: 1.2.1
  injectable: ^2.4.1
  intl: ^0.18.0
  json_annotation: ^4.9.0
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.0
  pocketbase: ^0.18.1
  posthog_flutter: ^4.4.1
  purchases_flutter: ^6.29.0
  sentry_flutter: ^8.1.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.0
  simple_mvvm: ^1.0.1
  supabase_flutter: ^2.5.2
  transparent_image: ^2.0.1
  universal_html: ^2.2.4
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  webfeed_revised: ^0.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
flutter:
  uses-material-design: true

  assets:
    - assets/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "logo"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  image_path_ios: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/logo.png"
    background_color: "#ffffff"
  # windows:
  #   generate: true
  #   image_path: "assets/logo.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  macos:
      generate: true
      image_path: "assets/logo.png"
