name: flutterfast
description: Build Flutter apps fast.
publish_to: none
version: 0.0.4+4

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  amplitude_flutter: ^3.16.1
  auto_route: ^7.8.4
  collection: ^1.18.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0  
  get_it: ^7.6.7
  google_fonts: ^6.1.0
  injectable: ^2.3.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.8.0
  package_info_plus: ^4.0.2
  sentry_flutter: ^7.16.0
  shared_preferences: ^2.2.2
  simple_mvvm: ^1.0.0
  transparent_image: ^2.0.1
  url_launcher: ^6.2.4

  #* RSS *#
  http: 1.2.0
  webfeed_revised: ^0.7.2
  #* RSS *#

  #* Subscriptions *#
  purchases_flutter: ^6.19.0
  #* Subscriptions *#

  #* Appwrite *#
  appwrite: 
    git: 
      url: https://github.com/jtmuller5/sdk-for-flutter
  #* Appwrite *#

  #* Firebase *#
  cloud_firestore: ^4.15.3
  firebase_auth: ^4.17.3
  firebase_core: ^2.25.3
  #* Firebase *#

  #* Supabase *#
  supabase_flutter: ^2.3.2
  #* Supabase *#

  #* Pocketbase *#
  pocketbase: ^0.17.1
  #* Pocketbase *#

  #* Google Sign In *#
  google_sign_in: ^6.2.1
  #* Google Sign In *#


# Build command
# Dev: dart run ../bin/fast.dart build
# dart run build_runner build --delete-conflicting-outputs
dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  monarch: ^3.5.3

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

# flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "logo"
  adaptive_icon_background: "#ffffff"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"
  image_path_ios: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#ffffff"
  # windows:
  #   generate: true
  #   image_path: "assets/images/logo.png"
  #   icon_size: 48 # min:48, max:256, default: 48
  macos:
      generate: true
      image_path: "assets/images/logo.png"